apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-secret
type: Opaque
data:
  # The token is base64 encoded
  token: TVRNek56UTVNakkxT0RjeU1qWTNOamc0TmcuR25UbU1wLm5KR0ZJYlFlUHVkSzdGSjk0QjBOMi1xVFhMZXlmUkNIczlhOXRr 