apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-discord-music-bot"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: discord-music-bot
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: discord-music-bot
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: discord-music-bot
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-discord-bot-secret"
              key: token 