apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-discord-bot-secret
type: Opaque
stringData:
  token: {{ .Values.discordToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry-credentials
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.mentalsj.uk": {
          "username": {{ .Values.registry.username | quote }},
          "password": {{ .Values.registry.password | quote }},
          "email": {{ .Values.registry.email | quote }},
          "auth": {{ printf "%s:%s" .Values.registry.username .Values.registry.password .Values.registry.email | b64enc | quote }}
        }
      }
    } 