apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: discord-bot

resources:
  - namespace.yaml
  - registry-secret.yaml
  - secret.yaml
  - deployment.yaml

images:
  - name: discord-music-bot
    newName: registry.mentalsj.uk/discord-music-bot
    newTag: latest

registry-secret:
  name: registry-credentials
  username: test
  password: test

