apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-credentials
  namespace: max-bot
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: secret-store    # Reference to your SecretStore configuration
    kind: SecretStore
  target:
    name: registry-credentials
    template:
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: docker-registry-credentials    # Key in your external secret store