apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord-music-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://your-git-repo-url.git
    targetRevision: HEAD
    path: discord-music-bot/helm
    helm:
      values: |
        discordToken: ""
        registry:
          server: ""
          username: ""
          password: ""
          email: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: discord-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 