apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord-music-bot
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: discord-music-bot=ghcr.io/donkelbinger/discord-music-bot
    argocd-image-updater.argoproj.io/discord-music-bot.update-strategy: newest-build
spec:
  project: default
  source:
    repoURL: https://your-git-repo-url.git
    targetRevision: HEAD
    path: discord-music-bot/helm
    helm:
      values: |
        # Discord Bot Configuration
        discordToken: ""
        authorizedGuildIds: ""
        
        # YouTube Configuration  
        youtubeCookieFile: ""
        
        # Bot Behavior Configuration
        logLevel: "INFO"
        commandPrefix: "/"
        maxQueueSize: "50"
        userQueueLimit: "20"
        voiceTimeout: "300"
        audioQuality: "medium"
        
        # Queue Persistence Configuration
        queuePersistence:
          enabled: "true"
          file: "data/queue_state.json"
          maxAgeHours: "24"
          saveIntervalMinutes: "5"
  destination:
    server: https://kubernetes.default.svc
    namespace: discord-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 