# Default values for discord-music-bot
replicaCount: 1

image:
  repository: ""
  tag: latest
  pullPolicy: Always

discordToken: ""

registry:
  server: ""
  username: ""
  password: ""
  email: ""
nameOverride: ""
fullnameOverride: "" 