name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          email: ${{ secrets.REGISTRY_EMAIL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_SERVER }}/discord-music-bot:latest
          cache-from: type=registry,ref=${{ secrets.REGISTRY_SERVER }}/discord-music-bot:buildcache
          cache-to: type=registry,ref=${{ secrets.REGISTRY_SERVER }}/discord-music-bot:buildcache,mode=max 