apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord-music-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://your-git-repo-url.git
    targetRevision: HEAD
    path: discord-music-bot/kustomization-2
    kustomize:
      images:
        - registry.mentalsj.uk/discord-music-bot:latest
      parameters:
        - name: DISCORD_TOKEN
          value: $DISCORD_TOKEN
        - name: REGISTRY_USERNAME
          value: $REGISTRY_USERNAME
        - name: REGISTRY_PASSWORD
          value: $REGISTRY_PASSWORD
        - name: REGISTRY_AUTH
          value: $REGISTRY_AUTH
  destination:
    server: https://kubernetes.default.svc
    namespace: discord-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 