apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: discord-bot

resources:
  - namespace.yaml
  - deployment.yaml

# Placeholder that will be replaced by ArgoCD
images:
  - name: discord-music-bot
    newName: registry.mentalsj.uk/discord-music-bot
    newTag: latest

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: discord-bot-secret
    type: Opaque
    literals:
      - token=$(discordToken)
  - name: registry-credentials
    type: kubernetes.io/dockerconfigjson
    literals:
      - .dockerconfigjson={"auths":{"registry.mentalsj.uk":{"username":"$(registry.username)","password":"$(registry.password)","auth":"$(echo -n '$(registry.username):$(registry.password)' | base64)"}}} 