apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: discord-bot

resources:
  - namespace.yaml
  - deployment.yaml

# Placeholder that will be replaced by ArgoCD
images:
  - name: discord-music-bot
    newName: registry.mentalsj.uk/discord-music-bot
    newTag: latest

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: discord-bot-secret
    type: Opaque
    envs:
      - .env.secret
  - name: registry-credentials
    type: kubernetes.io/dockerconfigjson
    envs:
      - .env.registry 