apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-secret
type: Opaque
stringData:
  token: ${DISCORD_TOKEN}
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.mentalsj.uk": {
          "username": "${REGISTRY_USERNAME}",
          "password": "${REGISTRY_PASSWORD}",
          "auth": "${REGISTRY_AUTH}"
        }
      }
    } 